RECORD_SCHEMA = {
    "type": "object",
    "required": ["paper", "enzyme_entity", "assay_context", "kinetic_or_activity", "evidence", "extraction_meta"],
    "properties": {
        "paper": {
            "type": "object",
            "required": ["paper_id", "doi", "title", "journal", "year", "url", "open_access", "fulltext_source"],
            "properties": {
                "paper_id": {"type": ["string", "null"]},
                "doi": {"type": ["string", "null"]},
                "title": {"type": ["string", "null"]},
                "journal": {"type": ["string", "null"]},
                "year": {"type": ["integer", "null"]},
                "url": {"type": ["string", "null"]},
                "open_access": {"type": ["boolean", "null"]},
                "fulltext_source": {"type": ["string", "null"]},
            },
        },
        "enzyme_entity": {
            "type": "object",
            "required": [
                "enzyme_name",
                "gene_name",
                "organism",
                "ec_number",
                "expression_system",
                "purification_level",
                "sequence_accession",
            ],
            "properties": {
                "enzyme_name": {"type": ["string", "null"]},
                "gene_name": {"type": ["string", "null"]},
                "organism": {"type": ["string", "null"]},
                "ec_number": {"type": ["string", "null"]},
                "expression_system": {"type": ["string", "null"]},
                "purification_level": {"type": ["string", "null"]},
                "sequence_accession": {"type": ["string", "null"]},
            },
        },
        "assay_context": {
            "type": "object",
            "required": [
                "assay_type",
                "substrate_name_raw",
                "substrate_name_normalized",
                "substrate_category",
                "mediator_or_coupler",
                "pH",
                "temperature_c",
                "buffer",
                "cofactors",
                "detection_method",
            ],
            "properties": {
                "assay_type": {"type": ["string", "null"]},
                "substrate_name_raw": {"type": ["string", "null"]},
                "substrate_name_normalized": {"type": ["string", "null"]},
                "substrate_category": {"type": ["string", "null"]},
                "mediator_or_coupler": {"type": ["string", "null"]},
                "pH": {"type": ["number", "null"]},
                "temperature_c": {"type": ["number", "null"]},
                "buffer": {"type": ["string", "null"]},
                "cofactors": {"type": ["string", "null"]},
                "detection_method": {"type": ["string", "null"]},
            },
        },
        "kinetic_or_activity": {
            "type": "object",
            "required": [
                "parameter_type",
                "value",
                "unit_raw",
                "unit_normalized",
                "value_normalized",
                "error",
                "notes",
            ],
            "properties": {
                "parameter_type": {"type": ["string", "null"]},
                "value": {"type": ["number", "null"]},
                "unit_raw": {"type": ["string", "null"]},
                "unit_normalized": {"type": ["string", "null"]},
                "value_normalized": {"type": ["number", "null"]},
                "error": {"type": ["string", "null"]},
                "notes": {"type": ["string", "null"]},
            },
        },
        "evidence": {
            "type": "object",
            "required": ["evidence_text", "location_hint", "confidence"],
            "properties": {
                "evidence_text": {"type": "string"},
                "location_hint": {"type": ["string", "null"]},
                "confidence": {"type": ["number", "null"]},
            },
        },
        "extraction_meta": {
            "type": "object",
            "required": ["extracted_by", "timestamp", "warnings", "needs_human_review"],
            "properties": {
                "extracted_by": {"type": ["string", "null"]},
                "timestamp": {"type": ["string", "null"]},
                "warnings": {"type": "array", "items": {"type": "string"}},
                "needs_human_review": {"type": "boolean"},
            },
        },
    },
}
